% run cellpose from matlab

imgpath = 'C:/Users/User/Desktop/img00.png';
img = double(imread(imgpath));

imgpy = py.matplotlib.pyplot.imread(imgpath);

% img = reshape(img, [size(img,1) size(img,2) 3]);
dev = py.mxnet.cpu();

mdl = py.cellpose.models.Cellpose(dev, pyargs('model_type', 'cyto'));

D = py.dict(pyargs(...
    'rescale',16,...
    'channels',py.list([0,0]),...
    'do_3D', false,...
    'net_avg', false,...
    'progress', py.None,...
    'tile', false,...
    'threshold', 0.4...
    ));

x = mdl.eval(py.list({imgpy}));

